baseURL = 'https://www.mwtmurphy.com/'
languageCode = 'en-gb'
author = 'Mitchell Murphy'
paginate = 3

theme = 'paper'
title = 'Mitchell Murphy'

[params]
  color = 'linen'

  github = 'mwtmurphy'
  linkedin = 'mwtmurphy'

  avatar = 'hi@mwtmurphy.com'
  name = 'Lead Data Scientist @ Motorway'
  bio = 'Building data products to improve decision-making.'

  enableGitInfo = true
  monoDarkIcon = true
  math = true

[module]
  [module.hugoVersion]
    extended = true